# Generated by Django 5.0.7 on 2024-08-08 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('motocykl', 'Motocykl'), ('osobowy', 'Osobowy'), ('ciężarowy', 'Ciężarowy')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('engine_capacity', models.PositiveIntegerField()),
                ('power', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('LPG', 'LPG')], max_length=10)),
                ('photo', models.ImageField(upload_to='vehicles_photos/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
